export const ActionTypes = {
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_LOGOUT: 'ADMIN_LOGOUT',
  FETCH_SERVICE_REQUESTS: 'FETCH_SERVICE_REQUESTS',
  UPDATE_SERVICE_REQUESTS: 'UPDATE_SERVICE_REQUESTS',
};
